Feature/cod 107 get api name from header in check api key
coders-app/coders-app-api-key-authenticator pull request #16
Opened 2023-02-27 17:42 UTC by benjaminrae

Ahora checkApiKey solo recibe targetApp como parametro, coge la apiKey del header X-API-KEY y apiName de X-API-NAME

He cambiado la implementacion de la peticion a redis, ahora uso el metodo `hget` para buscar en el hash guardado. Busca para el valor de appToAuthenticate en la coleccion de targetApp.

He actualizado los tests, la build y la documentacion

2023-02-27 17:49 UTC, mariogl requested changes

2023-02-27 17:49 UTC, mariogl commented on src/checkApiKey/checkApiKey.ts
>        (error as CustomError).statusCode = 401;
No me mola mucho esto de setear las propiedades después de haber creado el objeto. ¿No podríamos crear el CustomError en la línea 14 con esos dos datos?

2023-02-27 17:50 UTC, mariogl requested changes

2023-02-27 17:50 UTC, mariogl commented on src/setupTests.ts
> +const mockHashGet: (
Se empiezan a acumular los mocks en este archivo de setup, ¿los podemos sacar a otro sitio?

2023-02-27 17:53 UTC, benjaminrae commented on src/checkApiKey/checkApiKey.ts
>        (error as CustomError).statusCode = 401;
Si podriamos crearlo, lo hice asi porque es otro repo donde crearemos el mismo custom error, y de momento es solo para este next. Una opcion seria crear el CustomError en este repo y exportarlo a los demas, que opinas?

2023-02-27 17:54 UTC, benjaminrae commented on src/setupTests.ts
> +const mockHashGet: (
Podria hacer un modulo para mockear Redis, pero lo tendre que poner como parte del setup en jest.config

2023-02-27 17:58 UTC, MMLORENA commented on src/setupTests.ts
> +const mockHashGet: (
A mi me parece bien sacarlo y si hace falta añadirlo a setup jest.config se añade

2023-02-27 17:59 UTC, MMLORENA commented on src/checkApiKey/checkApiKey.ts
>        (error as CustomError).statusCode = 401;
Habría que darle una vuelta a los customError porque realmente los estamos creando en todas partes. Si vamos a implementar la factory estaría bueno usar el mismo sistema en todas las Apis e ideal sería poder exportarlo

2023-02-27 18:44 UTC, mariogl commented on src/checkApiKey/checkApiKey.ts
>        (error as CustomError).statusCode = 401;
Aunque sea sólo para este next, estás creando un Error, estás usando la clase CustomError para tiparlo y estás seteando las propiedades. Para mí eso es directamente un CustomError y se debería instanciar.

Me parece bien crear una factoría centralizada en un futuro cercano.

2023-02-27 18:47 UTC, mariogl commented on src/setupTests.ts
> +const mockHashGet: (
Hmmm... es verdad que los mocks de módulos son un poco más especiales, no podemos definirlos en un sitio y usarlos en otro fácilmente. ¿Por qué no sacamos los mocks como el de la función mockHashGet y dejamos aquí los mocks de módulos?

2023-02-27 19:40 UTC, MMLORENA commented on src/checkApiKey/checkApiKey.ts
>        (error as CustomError).statusCode = 401;
Pues nos esperamos a tener la factory si os parece en identity server y la replicamos hasta q haya algo común..

2023-03-02 08:42 UTC, benjaminrae commented on src/checkApiKey/checkApiKey.ts
>        (error as CustomError).statusCode = 401;
He creado un CustomError que luego podriamos cambiar para una factoria centralizado en un futuro

2023-03-02 08:43 UTC, benjaminrae commented on src/setupTests.ts
> +const mockHashGet: (
He quitado los mocked functions y los he puesto en una carpeta mocks, he dejado en setupTests solo el mock del modulo redis

2023-03-02 08:44 UTC, benjaminrae commented
He creado un CustomError y he movido las funciones mockeadas a una carpeta mocks

2023-03-03 12:02 UTC, MMLORENA approved these changes

2023-03-03 12:14 UTC, mariogl approved these changes

2023-03-03 12:14 UTC, merged